# Generated by Django 4.1.2 on 2022-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=15)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
